[project]
name = "aoc_2024"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "advent-of-code-data>=2.0.4",
    "black>=24.10.0",
    "isort>=5.13.2",
    "pyright>=1.1.389",
    "pytest>=8.3.3",
    "setuptools>=75.6.0",
]
